version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/order-service
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 200
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 200
      runas: ubuntu