version: 0.2

phases:
  pre_build:
    commands:
      - echo "Loggin to AWS ECR"
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 650142038379.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo "Building the docker image.."
      - DOCKER_BUILDKIT=1 docker build -t $REPOSITORY_NAME:$REPOSITORY_SLUG-latest --build-arg APP_ENV=$REPOSITORY_ENV_BRANCH --build-arg COMMAND_TYPE=main -f Dockerfile .
      - docker tag $REPOSITORY_NAME:$REPOSITORY_SLUG-latest 650142038379.dkr.ecr.ap-southeast-1.amazonaws.com/$REPOSITORY_NAME:$REPOSITORY_SLUG-latest
  post_build:
    commands:
      - echo "Push to ECR"
      - docker push 650142038379.dkr.ecr.ap-southeast-1.amazonaws.com/$REPOSITORY_NAME:$REPOSITORY_SLUG-latest
      - echo "Done ..."
artifacts:
  files:
    - '**/*'
  name: order-service-artifact
  discard-paths: no