// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "order-service/global/utils/model"

	mock "github.com/stretchr/testify/mock"

	models "order-service/app/models"
	openSearchRepositories "order-service/app/repositories/open_search"
)

// SalesOrderDetailOpenSearchRepositoryInterface is an autogenerated mock type for the SalesOrderDetailOpenSearchRepositoryInterface type
type SalesOrderDetailOpenSearchRepositoryInterface struct {
	mock.Mock
	openSearchRepositories.SalesOrderDetailOpenSearchRepositoryInterface
}

// Create provides a mock function with given fields: request, resultChan
func (_m *SalesOrderDetailOpenSearchRepositoryInterface) Create(request *models.SalesOrderDetailOpenSearch, resultChan chan *models.SalesOrderDetailOpenSearchChan) {
	_m.Called(request, resultChan)
}

// Get provides a mock function with given fields: request, isCountOnly, result
func (_m *SalesOrderDetailOpenSearchRepositoryInterface) Get(request *models.GetSalesOrderDetailRequest, isCountOnly bool, result chan *models.SalesOrderDetailsOpenSearchChan) {
	_m.Called(request, isCountOnly, result)
}

// generateSalesOrderDetailQueryOpenSearchResult provides a mock function with given fields: openSearchQueryJson, isCountOnly
func (_m *SalesOrderDetailOpenSearchRepositoryInterface) generateSalesOrderDetailQueryOpenSearchResult(openSearchQueryJson []byte, isCountOnly bool) (*models.SalesOrderDetailsOpenSearch, *model.ErrorLog) {
	ret := _m.Called(openSearchQueryJson, isCountOnly)

	var r0 *models.SalesOrderDetailsOpenSearch
	var r1 *model.ErrorLog
	if rf, ok := ret.Get(0).(func([]byte, bool) (*models.SalesOrderDetailsOpenSearch, *model.ErrorLog)); ok {
		return rf(openSearchQueryJson, isCountOnly)
	}
	if rf, ok := ret.Get(0).(func([]byte, bool) *models.SalesOrderDetailsOpenSearch); ok {
		r0 = rf(openSearchQueryJson, isCountOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SalesOrderDetailsOpenSearch)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, bool) *model.ErrorLog); ok {
		r1 = rf(openSearchQueryJson, isCountOnly)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorLog)
		}
	}

	return r0, r1
}

// generateSalesOrderDetailQueryOpenSearchTermRequest provides a mock function with given fields: term_field, term_value, request
func (_m *SalesOrderDetailOpenSearchRepositoryInterface) generateSalesOrderDetailQueryOpenSearchTermRequest(term_field string, term_value interface{}, request *models.GetSalesOrderDetailRequest) []byte {
	ret := _m.Called(term_field, term_value, request)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, interface{}, *models.GetSalesOrderDetailRequest) []byte); ok {
		r0 = rf(term_field, term_value, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

type mockConstructorTestingTNewSalesOrderDetailOpenSearchRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalesOrderDetailOpenSearchRepositoryInterface creates a new instance of SalesOrderDetailOpenSearchRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalesOrderDetailOpenSearchRepositoryInterface(t mockConstructorTestingTNewSalesOrderDetailOpenSearchRepositoryInterface) *SalesOrderDetailOpenSearchRepositoryInterface {
	mock := &SalesOrderDetailOpenSearchRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
