// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryOrderControllerInterface is an autogenerated mock type for the DeliveryOrderControllerInterface type
type DeliveryOrderControllerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// DeleteByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) DeleteByID(ctx *gin.Context) {
	_m.Called(ctx)
}

// DeleteDetailByDoID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) DeleteDetailByDoID(ctx *gin.Context) {
	_m.Called(ctx)
}

// DeleteDetailByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) DeleteDetailByID(ctx *gin.Context) {
	_m.Called(ctx)
}

// Export provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) Export(ctx *gin.Context) {
	_m.Called(ctx)
}

// ExportDetail provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) ExportDetail(ctx *gin.Context) {
	_m.Called(ctx)
}

// Get provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) Get(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetByID(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetBySalesmanID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetBySalesmanID(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDOJourneysByDoID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDOJourneysByDoID(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDetailById provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDetailById(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDetails provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDetails(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDetailsByDoId provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDetailsByDoId(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDoUploadErrorLogByDoUploadHistoryId provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDoUploadErrorLogByDoUploadHistoryId(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDoUploadErrorLogByReqId provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDoUploadErrorLogByReqId(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDoUploadHistories provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDoUploadHistories(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetDoUploadHistoriesById provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetDoUploadHistoriesById(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetJourneys provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetJourneys(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetSyncToKafkaHistories provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetSyncToKafkaHistories(ctx *gin.Context) {
	_m.Called(ctx)
}

// RetrySyncToKafka provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) RetrySyncToKafka(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) UpdateByID(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateDeliveryOrderDetailByDeliveryOrderID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) UpdateDeliveryOrderDetailByDeliveryOrderID(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateDeliveryOrderDetailByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) UpdateDeliveryOrderDetailByID(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewDeliveryOrderControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliveryOrderControllerInterface creates a new instance of DeliveryOrderControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliveryOrderControllerInterface(t mockConstructorTestingTNewDeliveryOrderControllerInterface) *DeliveryOrderControllerInterface {
	mock := &DeliveryOrderControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
