// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryOrderControllerInterface is an autogenerated mock type for the DeliveryOrderControllerInterface type
type DeliveryOrderControllerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// Get provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) Get(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetByID provides a mock function with given fields: ctx
func (_m *DeliveryOrderControllerInterface) GetByID(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewDeliveryOrderControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliveryOrderControllerInterface creates a new instance of DeliveryOrderControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliveryOrderControllerInterface(t mockConstructorTestingTNewDeliveryOrderControllerInterface) *DeliveryOrderControllerInterface {
	mock := &DeliveryOrderControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
