// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// HostToHostControllerInterface is an autogenerated mock type for the HostToHostControllerInterface type
type HostToHostControllerInterface struct {
	mock.Mock
}

// GetDeliveryOrders provides a mock function with given fields: ctx
func (_m *HostToHostControllerInterface) GetDeliveryOrders(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetSalesOrders provides a mock function with given fields: ctx
func (_m *HostToHostControllerInterface) GetSalesOrders(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewHostToHostControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewHostToHostControllerInterface creates a new instance of HostToHostControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHostToHostControllerInterface(t mockConstructorTestingTNewHostToHostControllerInterface) *HostToHostControllerInterface {
	mock := &HostToHostControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
