// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// SalesmanControllerInterface is an autogenerated mock type for the SalesmanControllerInterface type
type SalesmanControllerInterface struct {
	mock.Mock
}

// GetDeliveryOrders provides a mock function with given fields: ctx
func (_m *SalesmanControllerInterface) GetDeliveryOrders(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetSalesOrders provides a mock function with given fields: ctx
func (_m *SalesmanControllerInterface) GetSalesOrders(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewSalesmanControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalesmanControllerInterface creates a new instance of SalesmanControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalesmanControllerInterface(t mockConstructorTestingTNewSalesmanControllerInterface) *SalesmanControllerInterface {
	mock := &SalesmanControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
