// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateKafkaTopicCommandHandlerInterface is an autogenerated mock type for the CreateKafkaTopicCommandHandlerInterface type
type CreateKafkaTopicCommandHandlerInterface struct {
	mock.Mock
}

// CreateTopic provides a mock function with given fields: topic, partition
func (_m *CreateKafkaTopicCommandHandlerInterface) CreateTopic(topic string, partition int) error {
	ret := _m.Called(topic, partition)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(topic, partition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCreateKafkaTopicCommandHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateKafkaTopicCommandHandlerInterface creates a new instance of CreateKafkaTopicCommandHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateKafkaTopicCommandHandlerInterface(t mockConstructorTestingTNewCreateKafkaTopicCommandHandlerInterface) *CreateKafkaTopicCommandHandlerInterface {
	mock := &CreateKafkaTopicCommandHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
