// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "poc-order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// AgentBrandRepositoryInterface is an autogenerated mock type for the AgentBrandRepositoryInterface type
type AgentBrandRepositoryInterface struct {
	mock.Mock
}

// GetByAgentIDAndBrandID provides a mock function with given fields: agentID, brandID, countOnly, ctx, result
func (_m *AgentBrandRepositoryInterface) GetByAgentIDAndBrandID(agentID int, brandID int, countOnly bool, ctx context.Context, result chan *models.AgentBrandChan) {
	_m.Called(agentID, brandID, countOnly, ctx, result)
}

type mockConstructorTestingTNewAgentBrandRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAgentBrandRepositoryInterface creates a new instance of AgentBrandRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAgentBrandRepositoryInterface(t mockConstructorTestingTNewAgentBrandRepositoryInterface) *AgentBrandRepositoryInterface {
	mock := &AgentBrandRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
