// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// DeliveryOrderLogRepositoryInterface is an autogenerated mock type for the DeliveryOrderLogRepositoryInterface type
type DeliveryOrderLogRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, resultChan
func (_m *DeliveryOrderLogRepositoryInterface) GetByID(ID string, countOnly bool, ctx context.Context, resultChan chan *models.DeliveryOrderLogChan) {
	_m.Called(ID, countOnly, ctx, resultChan)
}

// Insert provides a mock function with given fields: request, ctx, result
func (_m *DeliveryOrderLogRepositoryInterface) Insert(request *models.DeliveryOrderLog, ctx context.Context, result chan *models.DeliveryOrderLogChan) {
	_m.Called(request, ctx, result)
}

// UpdateByID provides a mock function with given fields: ID, request, ctx, result
func (_m *DeliveryOrderLogRepositoryInterface) UpdateByID(ID string, request *models.DeliveryOrderLog, ctx context.Context, result chan *models.DeliveryOrderLogChan) {
	_m.Called(ID, request, ctx, result)
}

type mockConstructorTestingTNewDeliveryOrderLogRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliveryOrderLogRepositoryInterface creates a new instance of DeliveryOrderLogRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliveryOrderLogRepositoryInterface(t mockConstructorTestingTNewDeliveryOrderLogRepositoryInterface) *DeliveryOrderLogRepositoryInterface {
	mock := &DeliveryOrderLogRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
