// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "poc-order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// OrderStatusRepositoryInterface is an autogenerated mock type for the OrderStatusRepositoryInterface type
type OrderStatusRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, result
func (_m *OrderStatusRepositoryInterface) GetByID(ID int, countOnly bool, ctx context.Context, result chan *models.OrderStatusChan) {
	_m.Called(ID, countOnly, ctx, result)
}

// GetByNameAndType provides a mock function with given fields: name, statusType, countOnly, ctx, result
func (_m *OrderStatusRepositoryInterface) GetByNameAndType(name string, statusType string, countOnly bool, ctx context.Context, result chan *models.OrderStatusChan) {
	_m.Called(name, statusType, countOnly, ctx, result)
}

type mockConstructorTestingTNewOrderStatusRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderStatusRepositoryInterface creates a new instance of OrderStatusRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderStatusRepositoryInterface(t mockConstructorTestingTNewOrderStatusRepositoryInterface) *OrderStatusRepositoryInterface {
	mock := &OrderStatusRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
