// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// SalesOrderLogRepositoryInterface is an autogenerated mock type for the SalesOrderLogRepositoryInterface type
type SalesOrderLogRepositoryInterface struct {
	mock.Mock
}
func (_m *SalesOrderLogRepositoryInterface) Get(request *models.SalesOrderEventLogRequest, countOnly bool, ctx context.Context, resultChan chan *models.GetSalesOrderLogsChan) {
	_m.Called(request, countOnly, ctx, resultChan)
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, resultChan
func (_m *SalesOrderLogRepositoryInterface) GetByID(ID string, countOnly bool, ctx context.Context, resultChan chan *models.GetSalesOrderLogChan) {
	_m.Called(ID, countOnly, ctx, resultChan)
}
func (_m *SalesOrderLogRepositoryInterface) GetByCollumn(collumnName string, value string, countOnly bool, ctx context.Context, resultChan chan *models.SalesOrderLogChan){
	_m.Called(collumnName, value, countOnly, ctx, resultChan)
}

// Insert provides a mock function with given fields: request, ctx, result
func (_m *SalesOrderLogRepositoryInterface) Insert(request *models.SalesOrderLog, ctx context.Context, result chan *models.SalesOrderLogChan) {
	_m.Called(request, ctx, result)
}

// UpdateByID provides a mock function with given fields: ID, request, ctx, result
func (_m *SalesOrderLogRepositoryInterface) UpdateByID(ID string, request *models.SalesOrderLog, ctx context.Context, result chan *models.SalesOrderLogChan) {
	_m.Called(ID, request, ctx, result)
}

type mockConstructorTestingTNewSalesOrderLogRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalesOrderLogRepositoryInterface creates a new instance of SalesOrderLogRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalesOrderLogRepositoryInterface(t mockConstructorTestingTNewSalesOrderLogRepositoryInterface) *SalesOrderLogRepositoryInterface {
	mock := &SalesOrderLogRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
