// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateDeliveryOrderConsumerHandlerInterface is an autogenerated mock type for the CreateDeliveryOrderConsumerHandlerInterface type
type CreateDeliveryOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *CreateDeliveryOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewCreateDeliveryOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateDeliveryOrderConsumerHandlerInterface creates a new instance of CreateDeliveryOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateDeliveryOrderConsumerHandlerInterface(t mockConstructorTestingTNewCreateDeliveryOrderConsumerHandlerInterface) *CreateDeliveryOrderConsumerHandlerInterface {
	mock := &CreateDeliveryOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
