// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateSalesOrderConsumerHandlerInterface is an autogenerated mock type for the CreateSalesOrderConsumerHandlerInterface type
type CreateSalesOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *CreateSalesOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewCreateSalesOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateSalesOrderConsumerHandlerInterface creates a new instance of CreateSalesOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateSalesOrderConsumerHandlerInterface(t mockConstructorTestingTNewCreateSalesOrderConsumerHandlerInterface) *CreateSalesOrderConsumerHandlerInterface {
	mock := &CreateSalesOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
