// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteSalesOrderDetailConsumerHandlerInterface is an autogenerated mock type for the DeleteSalesOrderDetailConsumerHandlerInterface type
type DeleteSalesOrderDetailConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *DeleteSalesOrderDetailConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewDeleteSalesOrderDetailConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteSalesOrderDetailConsumerHandlerInterface creates a new instance of DeleteSalesOrderDetailConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteSalesOrderDetailConsumerHandlerInterface(t mockConstructorTestingTNewDeleteSalesOrderDetailConsumerHandlerInterface) *DeleteSalesOrderDetailConsumerHandlerInterface {
	mock := &DeleteSalesOrderDetailConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
