// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteSalesOrderConsumerHandlerInterface is an autogenerated mock type for the DeleteSalesOrderConsumerHandlerInterface type
type DeleteSalesOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *DeleteSalesOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewDeleteSalesOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteSalesOrderConsumerHandlerInterface creates a new instance of DeleteSalesOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteSalesOrderConsumerHandlerInterface(t mockConstructorTestingTNewDeleteSalesOrderConsumerHandlerInterface) *DeleteSalesOrderConsumerHandlerInterface {
	mock := &DeleteSalesOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
