// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteDeliveryOrderDetailConsumerHandlerInterface is an autogenerated mock type for the DeleteDeliveryOrderDetailConsumerHandlerInterface type
type DeleteDeliveryOrderDetailConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *DeleteDeliveryOrderDetailConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewDeleteDeliveryOrderDetailConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteDeliveryOrderDetailConsumerHandlerInterface creates a new instance of DeleteDeliveryOrderDetailConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteDeliveryOrderDetailConsumerHandlerInterface(t mockConstructorTestingTNewDeleteDeliveryOrderDetailConsumerHandlerInterface) *DeleteDeliveryOrderDetailConsumerHandlerInterface {
	mock := &DeleteDeliveryOrderDetailConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
