// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteDeliveryOrderConsumerHandlerInterface is an autogenerated mock type for the DeleteDeliveryOrderConsumerHandlerInterface type
type DeleteDeliveryOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *DeleteDeliveryOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewDeleteDeliveryOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteDeliveryOrderConsumerHandlerInterface creates a new instance of DeleteDeliveryOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteDeliveryOrderConsumerHandlerInterface(t mockConstructorTestingTNewDeleteDeliveryOrderConsumerHandlerInterface) *DeleteDeliveryOrderConsumerHandlerInterface {
	mock := &DeleteDeliveryOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
