// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExportSalesOrderDetailConsumerHandlerInterface is an autogenerated mock type for the ExportSalesOrderDetailConsumerHandlerInterface type
type ExportSalesOrderDetailConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *ExportSalesOrderDetailConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewExportSalesOrderDetailConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewExportSalesOrderDetailConsumerHandlerInterface creates a new instance of ExportSalesOrderDetailConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExportSalesOrderDetailConsumerHandlerInterface(t mockConstructorTestingTNewExportSalesOrderDetailConsumerHandlerInterface) *ExportSalesOrderDetailConsumerHandlerInterface {
	mock := &ExportSalesOrderDetailConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
