// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExportSalesOrderConsumerHandlerInterface is an autogenerated mock type for the ExportSalesOrderConsumerHandlerInterface type
type ExportSalesOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *ExportSalesOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewExportSalesOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewExportSalesOrderConsumerHandlerInterface creates a new instance of ExportSalesOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExportSalesOrderConsumerHandlerInterface(t mockConstructorTestingTNewExportSalesOrderConsumerHandlerInterface) *ExportSalesOrderConsumerHandlerInterface {
	mock := &ExportSalesOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
