// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExportDeliveryOrderConsumerHandlerInterface is an autogenerated mock type for the ExportDeliveryOrderConsumerHandlerInterface type
type ExportDeliveryOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *ExportDeliveryOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewExportDeliveryOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewExportDeliveryOrderConsumerHandlerInterface creates a new instance of ExportDeliveryOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExportDeliveryOrderConsumerHandlerInterface(t mockConstructorTestingTNewExportDeliveryOrderConsumerHandlerInterface) *ExportDeliveryOrderConsumerHandlerInterface {
	mock := &ExportDeliveryOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
