// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExportDeliveryOrderDetailConsumerHandlerInterface is an autogenerated mock type for the ExportDeliveryOrderDetailConsumerHandlerInterface type
type ExportDeliveryOrderDetailConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *ExportDeliveryOrderDetailConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewExportDeliveryOrderDetailConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewExportDeliveryOrderDetailConsumerHandlerInterface creates a new instance of ExportDeliveryOrderDetailConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExportDeliveryOrderDetailConsumerHandlerInterface(t mockConstructorTestingTNewExportDeliveryOrderDetailConsumerHandlerInterface) *ExportDeliveryOrderDetailConsumerHandlerInterface {
	mock := &ExportDeliveryOrderDetailConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
