// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateSalesOrderDetailConsumerHandlerInterface is an autogenerated mock type for the UpdateSalesOrderDetailConsumerHandlerInterface type
type UpdateSalesOrderDetailConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UpdateSalesOrderDetailConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUpdateSalesOrderDetailConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateSalesOrderDetailConsumerHandlerInterface creates a new instance of UpdateSalesOrderDetailConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateSalesOrderDetailConsumerHandlerInterface(t mockConstructorTestingTNewUpdateSalesOrderDetailConsumerHandlerInterface) *UpdateSalesOrderDetailConsumerHandlerInterface {
	mock := &UpdateSalesOrderDetailConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
