// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateSalesOrderConsumerHandlerInterface is an autogenerated mock type for the UpdateSalesOrderConsumerHandlerInterface type
type UpdateSalesOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UpdateSalesOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUpdateSalesOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateSalesOrderConsumerHandlerInterface creates a new instance of UpdateSalesOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateSalesOrderConsumerHandlerInterface(t mockConstructorTestingTNewUpdateSalesOrderConsumerHandlerInterface) *UpdateSalesOrderConsumerHandlerInterface {
	mock := &UpdateSalesOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
