// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateDeliveryOrderConsumerHandlerInterface is an autogenerated mock type for the UpdateDeliveryOrderConsumerHandlerInterface type
type UpdateDeliveryOrderConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UpdateDeliveryOrderConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUpdateDeliveryOrderConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateDeliveryOrderConsumerHandlerInterface creates a new instance of UpdateDeliveryOrderConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateDeliveryOrderConsumerHandlerInterface(t mockConstructorTestingTNewUpdateDeliveryOrderConsumerHandlerInterface) *UpdateDeliveryOrderConsumerHandlerInterface {
	mock := &UpdateDeliveryOrderConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
