// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UploadSOSJFileConsumerHandlerInterface is an autogenerated mock type for the UploadSOSJFileConsumerHandlerInterface type
type UploadSOSJFileConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UploadSOSJFileConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUploadSOSJFileConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadSOSJFileConsumerHandlerInterface creates a new instance of UploadSOSJFileConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadSOSJFileConsumerHandlerInterface(t mockConstructorTestingTNewUploadSOSJFileConsumerHandlerInterface) *UploadSOSJFileConsumerHandlerInterface {
	mock := &UploadSOSJFileConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
