// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UploadSOFileConsumerHandlerInterface is an autogenerated mock type for the UploadSOFileConsumerHandlerInterface type
type UploadSOFileConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UploadSOFileConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUploadSOFileConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadSOFileConsumerHandlerInterface creates a new instance of UploadSOFileConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadSOFileConsumerHandlerInterface(t mockConstructorTestingTNewUploadSOFileConsumerHandlerInterface) *UploadSOFileConsumerHandlerInterface {
	mock := &UploadSOFileConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
