// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UploadSOSJItemConsumerHandlerInterface is an autogenerated mock type for the UploadSOSJItemConsumerHandlerInterface type
type UploadSOSJItemConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UploadSOSJItemConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUploadSOSJItemConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadSOSJItemConsumerHandlerInterface creates a new instance of UploadSOSJItemConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadSOSJItemConsumerHandlerInterface(t mockConstructorTestingTNewUploadSOSJItemConsumerHandlerInterface) *UploadSOSJItemConsumerHandlerInterface {
	mock := &UploadSOSJItemConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
