// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UploadDOFileConsumerHandlerInterface is an autogenerated mock type for the UploadDOFileConsumerHandlerInterface type
type UploadDOFileConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UploadDOFileConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUploadDOFileConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadDOFileConsumerHandlerInterface creates a new instance of UploadDOFileConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadDOFileConsumerHandlerInterface(t mockConstructorTestingTNewUploadDOFileConsumerHandlerInterface) *UploadDOFileConsumerHandlerInterface {
	mock := &UploadDOFileConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
