// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UploadSOItemConsumerHandlerInterface is an autogenerated mock type for the UploadSOItemConsumerHandlerInterface type
type UploadSOItemConsumerHandlerInterface struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields:
func (_m *UploadSOItemConsumerHandlerInterface) ProcessMessage() {
	_m.Called()
}

type mockConstructorTestingTNewUploadSOItemConsumerHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadSOItemConsumerHandlerInterface creates a new instance of UploadSOItemConsumerHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadSOItemConsumerHandlerInterface(t mockConstructorTestingTNewUploadSOItemConsumerHandlerInterface) *UploadSOItemConsumerHandlerInterface {
	mock := &UploadSOItemConsumerHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
