package constants

func DELIVERY_ORDER_EXPORT_HEADER() []string {
	return []string{
		"DOStatus",
		"DODate",
		"SJNo",
		"DONO",
		"OrderNo",
		"SODate",
		"SONO",
		"SOSource",
		"AgentID",
		"AgentName",
		"GudangID",
		"GudangName",
		"BrandID",
		"BrandName",
		"KodeSalesman",
		"Salesman",
		"KategoriToko",
		"KodeTokoDBO",
		"KodeToko",
		"NamaToko",
		"KodeKecamatan",
		"Kecamatan",
		"Kode City",
		"City",
		"KodeProvince",
		"Province",
		"DOAmount",
		"NamaSupir",
		"PlatNo",
		"Catatan",
		"CreatedDate",
		"LastUpdate",
		"UserIDCreated",
		"UserIDModified"}
}

func DELIVERY_ORDER_DETAIL_EXPORT_HEADER() []string {
	return []string{
		"DOStatus",
		"DODate",
		"SJNo",
		"DONO",
		"SODate",
		"SONO",
		"SOSource",
		"AgentID",
		"AgentName",
		"GudangID",
		"GudangName",
		"BrandID",
		"BrandName",
		"KodeSalesman",
		"Salesman",
		"KategoriToko",
		"KodeTokoDBO",
		"KodeToko",
		"NamaToko",
		"KodeKecamatan",
		"Kecamatan",
		"Kode City",
		"City",
		"KodeProvince",
		"Province",
		"BrandID",
		"BrandName",
		"KategoriID_L1",
		"KategoriName_L1",
		"KategoriID_Last",
		"KategoriName_Last",
		"ItemCode",
		"ItemName",
		"UnitSatuan",
		"Price",
		"SOQty",
		"SOQty_Sisa",
		"DOQty",
		"DOAmount",
		"CreatedDate",
		"LastUpdate",
		"UserIDCreated",
		"UserIDModified"}
}

func SALES_ORDER_EXPORT_HEADER() []string {
	return []string{
		"SOStatus",
		"SOSource",
		"KodeReferralOrder",
		"OrderNo",
		"SONO",
		"SODate",
		"DistributorID",
		"DistributorName",
		"KodeSalesman",
		"Salesman",
		"TokoType",
		"KodeTokoDBO",
		"KodeToko",
		"TokoName",
		"KodeKecamatan",
		"Kecamatan",
		"KodeCity",
		"City",
		"KodeProvince",
		"Province",
		"BrandID",
		"BrandName",
		"SOAmount",
		"DOAmount",
		"OrderNotes",
		"InternalNotes",
		"AlasanCancel",
		"AlasanReject",
		"SORefDate",
		"CreatedDate",
		"LastUpdate",
		"UserIDCreated",
		"UserIDModified"}
}
