package constants

func DELIVERY_ORDER_EXPORT_HEADER() []string {
	return []string{
		"do_status",
		"do_date",
		"sj_no",
		"do_no",
		"order_no",
		"so_date",
		"so_no",
		"so_source",
		"agent_id",
		"agent_name",
		"gudang_id",
		"gudang_name",
		"brand_id",
		"brand_name",
		"kode_salesman",
		"salesman",
		"kategory_toko",
		"kode_toko_dbo",
		"kode_toko",
		"nama_toko",
		"kode_kecamatan",
		"kecamatan",
		"kode_city",
		"city",
		"kode_province",
		"province",
		"do_amount",
		"nama_supir",
		"plat_no",
		"catatan",
		"created_date",
		"updated_date",
		"user_id_created",
		"user_id_modified"}
}
