package constants

const (
	SALES_ORDERS_PATH                 = "sales-orders"
	SALES_ORDER_DETAILS_PATH          = "sales-order-details"
	DELIVERY_ORDERS_PATH              = "delivery-orders"
	AGENT_PATH                        = "agent"
	STORES_PATH                       = "stores"
	SALESMANS_PATH                    = "salesman"
	HEALTH_CHECK_PATH                 = "health-check"
	HOST_TO_HOST_PATH                 = "h2h"
	DELIVERY_ORDER_EXPORT_PATH        = "apis.dbo.dev/noncore-assets/download/excel/delivery_order"
	DELIVERY_ORDER_DETAIL_EXPORT_PATH = "apis.dbo.dev/noncore-assets/download/excel/delivery_order_detail"
	SALES_ORDER_EXPORT_PATH           = "apis.dbo.dev/noncore-assets/download/excel/sales_order"
	SALES_ORDER_DETAIL_EXPORT_PATH    = "apis.dbo.dev/noncore-assets/download/excel/sales_order_detail"
	UPLOAD_SOSJ_PATH                  = "upload-sosj"
	UPLOAD_DO_PATH                    = "upload-delivery-orders"
	UPLOAD_SO_PATH                    = "upload-sales-orders"
	SOSJ_PATH                         = "sosj"
	UPLOAD_HISTORIES_PATH             = "upload-histories"
	// DELIVERY_ORDER_EXPORT_PATH="https://lambda-upload-srv.s3.ap-southeast-1.amazonaws.com/lambda-upload-srv/order-service/export-delivery-orders"
	// DELIVERY_ORDER_DETAIL_EXPORT_PATH="https://lambda-upload-srv.s3.ap-southeast-1.amazonaws.com/lambda-upload-srv/order-service/export-delivery-order-details"
	// SALES_ORDER_EXPORT_PATH="https://lambda-upload-srv.s3.ap-southeast-1.amazonaws.com/lambda-upload-srv/order-service/export-sales-orders"
	// SALES_ORDER_DETAIL_EXPORT_PATH="https://lambda-upload-srv.s3.ap-southeast-1.amazonaws.com/lambda-upload-srv/order-service/export-sales-orders-details"
)
