// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DeliveryOrderJourneyRepositoryInterface is an autogenerated mock type for the DeliveryOrderJourneyRepositoryInterface type
type DeliveryOrderJourneyRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: request, countOnly, ctx, result
func (_m *DeliveryOrderJourneyRepositoryInterface) Get(request *models.DeliveryOrderJourneysRequest, countOnly bool, ctx context.Context, result chan *models.DeliveryOrderJourneysChan) {
	_m.Called(request, countOnly, ctx, result)
}

// GetByDoID provides a mock function with given fields: doID, countOnly, ctx, resultChan
func (_m *DeliveryOrderJourneyRepositoryInterface) GetByDoID(doID int, countOnly bool, ctx context.Context, resultChan chan *models.DeliveryOrderJourneysChan) {
	_m.Called(doID, countOnly, ctx, resultChan)
}

// InsertFromDO provides a mock function with given fields: request, remarks, now, ctx, result
func (_m *DeliveryOrderJourneyRepositoryInterface) InsertFromDO(request *models.DeliveryOrder, remarks string, now time.Time, ctx context.Context, result chan *models.DeliveryOrderJourneyChan) {
	_m.Called(request, remarks, now, ctx, result)
}

type mockConstructorTestingTNewDeliveryOrderJourneyRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliveryOrderJourneyRepositoryInterface creates a new instance of DeliveryOrderJourneyRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliveryOrderJourneyRepositoryInterface(t mockConstructorTestingTNewDeliveryOrderJourneyRepositoryInterface) *DeliveryOrderJourneyRepositoryInterface {
	mock := &DeliveryOrderJourneyRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
