// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// DoUploadErrorLogsRepositoryInterface is an autogenerated mock type for the DoUploadErrorLogsRepositoryInterface type
type DoUploadErrorLogsRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: request, countOnly, ctx, resultChan
func (_m *DoUploadErrorLogsRepositoryInterface) Get(request *models.GetDoUploadErrorLogsRequest, countOnly bool, ctx context.Context, resultChan chan *models.DoUploadErrorLogsChan) {
	_m.Called(request, countOnly, ctx, resultChan)
}

// Insert provides a mock function with given fields: request, ctx, resultChan
func (_m *DoUploadErrorLogsRepositoryInterface) Insert(request *models.DoUploadErrorLog, ctx context.Context, resultChan chan *models.DoUploadErrorLogChan) {
	_m.Called(request, ctx, resultChan)
}

type mockConstructorTestingTNewDoUploadErrorLogsRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDoUploadErrorLogsRepositoryInterface creates a new instance of DoUploadErrorLogsRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDoUploadErrorLogsRepositoryInterface(t mockConstructorTestingTNewDoUploadErrorLogsRepositoryInterface) *DoUploadErrorLogsRepositoryInterface {
	mock := &DoUploadErrorLogsRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
