// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// SalesOrderDetailJourneysRepositoryInterface is an autogenerated mock type for the SalesOrderDetailJourneysRepositoryInterface type
type SalesOrderDetailJourneysRepositoryInterface struct {
	mock.Mock
}

// Insert provides a mock function with given fields: request, ctx, resultChan
func (_m *SalesOrderDetailJourneysRepositoryInterface) Insert(request *models.SalesOrderDetailJourneys, ctx context.Context, resultChan chan *models.SalesOrderDetailJourneysChan) {
	_m.Called(request, ctx, resultChan)
}

type mockConstructorTestingTNewSalesOrderDetailJourneysRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalesOrderDetailJourneysRepositoryInterface creates a new instance of SalesOrderDetailJourneysRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalesOrderDetailJourneysRepositoryInterface(t mockConstructorTestingTNewSalesOrderDetailJourneysRepositoryInterface) *SalesOrderDetailJourneysRepositoryInterface {
	mock := &SalesOrderDetailJourneysRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
