// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// SalesOrderJourneysRepositoryInterface is an autogenerated mock type for the SalesOrderJourneysRepositoryInterface type
type SalesOrderJourneysRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: request, countOnly, ctx, result
func (_m *SalesOrderJourneysRepositoryInterface) Get(request *models.SalesOrderJourneyRequest, countOnly bool, ctx context.Context, result chan *models.SalesOrdersJourneysChan) {
	_m.Called(request, countOnly, ctx, result)
}

// GetBySoId provides a mock function with given fields: ID, countOnly, ctx, resultChan
func (_m *SalesOrderJourneysRepositoryInterface) GetBySoId(ID int, countOnly bool, ctx context.Context, resultChan chan *models.SalesOrdersJourneysChan) {
	_m.Called(ID, countOnly, ctx, resultChan)
}

// Insert provides a mock function with given fields: request, ctx, resultChan
func (_m *SalesOrderJourneysRepositoryInterface) Insert(request *models.SalesOrderJourneys, ctx context.Context, resultChan chan *models.SalesOrderJourneysChan) {
	_m.Called(request, ctx, resultChan)
}

type mockConstructorTestingTNewSalesOrderJourneysRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalesOrderJourneysRepositoryInterface creates a new instance of SalesOrderJourneysRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalesOrderJourneysRepositoryInterface(t mockConstructorTestingTNewSalesOrderJourneysRepositoryInterface) *SalesOrderJourneysRepositoryInterface {
	mock := &SalesOrderJourneysRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
