// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// SoUploadErrorLogsRepositoryInterface is an autogenerated mock type for the SoUploadErrorLogsRepositoryInterface type
type SoUploadErrorLogsRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: request, countOnly, ctx, resultChan
func (_m *SoUploadErrorLogsRepositoryInterface) Get(request *models.GetSoUploadErrorLogsRequest, countOnly bool, ctx context.Context, resultChan chan *models.SoUploadErrorLogsChan) {
	_m.Called(request, countOnly, ctx, resultChan)
}

// Insert provides a mock function with given fields: request, ctx, resultChan
func (_m *SoUploadErrorLogsRepositoryInterface) Insert(request *models.SoUploadErrorLog, ctx context.Context, resultChan chan *models.SoUploadErrorLogChan) {
	_m.Called(request, ctx, resultChan)
}

type mockConstructorTestingTNewSoUploadErrorLogsRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSoUploadErrorLogsRepositoryInterface creates a new instance of SoUploadErrorLogsRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSoUploadErrorLogsRepositoryInterface(t mockConstructorTestingTNewSoUploadErrorLogsRepositoryInterface) *SoUploadErrorLogsRepositoryInterface {
	mock := &SoUploadErrorLogsRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
