// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// AgentRepositoryInterface is an autogenerated mock type for the AgentRepositoryInterface type
type AgentRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, result
func (_m *AgentRepositoryInterface) GetByID(ID int, countOnly bool, ctx context.Context, result chan *models.AgentChan) {
	_m.Called(ID, countOnly, ctx, result)
}

type mockConstructorTestingTNewAgentRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAgentRepositoryInterface creates a new instance of AgentRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAgentRepositoryInterface(t mockConstructorTestingTNewAgentRepositoryInterface) *AgentRepositoryInterface {
	mock := &AgentRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
