// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "poc-order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// BrandRepositoryInterface is an autogenerated mock type for the BrandRepositoryInterface type
type BrandRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, result
func (_m *BrandRepositoryInterface) GetByID(ID int, countOnly bool, ctx context.Context, result chan *models.BrandChan) {
	_m.Called(ID, countOnly, ctx, result)
}

type mockConstructorTestingTNewBrandRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewBrandRepositoryInterface creates a new instance of BrandRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBrandRepositoryInterface(t mockConstructorTestingTNewBrandRepositoryInterface) *BrandRepositoryInterface {
	mock := &BrandRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
