// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// PusherRepositoryInterface is an autogenerated mock type for the PusherRepositoryInterface type
type PusherRepositoryInterface struct {
	mock.Mock
}

// Publish provides a mock function with given fields: _a0
func (_m *PusherRepositoryInterface) Publish(_a0 *models.Pusher) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Pusher) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPusherRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewPusherRepositoryInterface creates a new instance of PusherRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPusherRepositoryInterface(t mockConstructorTestingTNewPusherRepositoryInterface) *PusherRepositoryInterface {
	mock := &PusherRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
