// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// UomRepositoryInterface is an autogenerated mock type for the UomRepositoryInterface type
type UomRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, result
func (_m *UomRepositoryInterface) GetByID(ID int, countOnly bool, ctx context.Context, result chan *models.UomChan) {
	_m.Called(ID, countOnly, ctx, result)
}

type mockConstructorTestingTNewUomRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUomRepositoryInterface creates a new instance of UomRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUomRepositoryInterface(t mockConstructorTestingTNewUomRepositoryInterface) *UomRepositoryInterface {
	mock := &UomRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
