// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "poc-order-service/app/models"

	mock "github.com/stretchr/testify/mock"
)

// WarehouseRepositoryInterface is an autogenerated mock type for the WarehouseRepositoryInterface type
type WarehouseRepositoryInterface struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ID, countOnly, ctx, result
func (_m *WarehouseRepositoryInterface) GetByID(ID int, countOnly bool, ctx context.Context, result chan *models.WarehouseChan) {
	_m.Called(ID, countOnly, ctx, result)
}

type mockConstructorTestingTNewWarehouseRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewWarehouseRepositoryInterface creates a new instance of WarehouseRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWarehouseRepositoryInterface(t mockConstructorTestingTNewWarehouseRepositoryInterface) *WarehouseRepositoryInterface {
	mock := &WarehouseRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
